### ISSUE TITLE
Pebble write-throughput benchmarks

### ISSUE THREAD

**Issue by nicktrav** [cockroachdb/pebble#1369]
This is a "meta" ticket for tracking the working of adding a write-throughput benchmark for Pebble. 

The original motivation for this was to explore the limits of Pebble's write path and provide a baseline on which we can measure and track improvements over time. We want to see how much write load we can drive at Pebble "sustainably". To begin with, "sustainable" is loosely defined as the maximum amount of write load Pebble can tolerate without exceeding one or more heuristics. Initially, these heuristics are:

- write stall detection (typically caused by filling up the memtable queue)
- exceeding 1000 files in L0
- exceeding a read-amp of 10 in L0 (i.e. 10 sub-levels in L0)

The values for the limits are the same limits we use in Admission Control in Cockroach (see [here](https://github.com/cockroachdb/cockroach/blob/8f24d350aef508e14b74546fc5f24f52a51548d9/pkg/util/admission/granter.go#L790-L804)), and the default Pebble options we use for the existing YCSB benchmarks (see [here](https://github.com/cockroachdb/pebble/blob/447349ef50e67d8766e3c1f5bb14eb6de63afd65/cmd/pebble/db.go#L56)).

---

Items of work:

- [X] Add write-throughput benchmark harness: #1345
- [X] Add write-throughput data parser: #1364
- [x] Add a roachtest to run the benchmark nightly: cockroachdb/cockroach#72632
- [x] Add data visualization to Pebble Benchmarks page: #1374 
- [x] Configure TeamCity to run the write-throughput benchmark nightly
