### ISSUE TITLE
db: virtual sstable meta issue

### ISSUE THREAD

**Issue by bananabrick** [cockroachdb/pebble#2336]
This issue tracks the steps to mark finish the virtual sstable project.

- [x] Virtual sstable data structure changes https://github.com/cockroachdb/pebble/pull/2352
- [x] Virtual sstable read path https://github.com/cockroachdb/pebble/pull/2288
  - [ ] Compute virtual sstable table stats asynchronously.
- [ ] version edit decoding encoding https://github.com/cockroachdb/pebble/pull/2484
- [ ] https://github.com/cockroachdb/pebble/issues/1683 Virtual sstable write path.
  - [ ] Virtual sstable space amp heuristic test https://github.com/cockroachdb/pebble/issues/2323
- [ ] Format major version gating for virtual sstables
- [ ] Sweep through todos in code related to virtual sstables to make sure its covered.

**Comment by bananabrick** [comment]
Splitting the work here into different issues. Closing this out.
